version: "3.9"
services:
  mongoDB:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    # env_file:
    #   - .env/envFileName
  backend:
    build: ./backend
    # build:
    #   -context: ./backend
    #   dockerfile: Dockerfile
    # args:
    #   - arg here
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongoDB
    # env_file:
    #   - .env/envFileName
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    # -it
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
