FROM python:latest

WORKDIR .

COPY . .

CMD [ "python", "randomNumber.py" ]


#  docker run command

#  docker build -t python_on_docker .
#  docker run -it python_on_docker 

#  where -it,  interactive mode